version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Pritam@123
      - MYSQL_DATABASE=message_mingle
      - MYSQL_USER=pritam
      - MYSQL_PASSWORD=Pritam@123

  spring-boot-app:
    image: message_mingle:latest
    container_name: spring_boot_app
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_USERNAME=pritam
      - SPRING_DATASOURCE_PASSWORD=Pritam@123
    depends_on:
      - mysql

    volumes:
      mysql-data: {}
